# https://numtide.github.io/devshell
imports = ["language.go"]

[language.go]
package = "go_1_21"

[devshell]
packages = [
    "go-tools",
    "gopls",
    "go-outline",
    "gocode",
    "gopkgs",
    "gocode-gomod",
    "godef",
    "golint",
    "delve",
    "impl",
    "mockgen",
    "bazel-gazelle",

    "cmake",
    "gnumake",
    "protobuf",
    "clang",
    "rustup",
    "gdb",
    "typos",

    "fish"
]
